# -*- coding: utf-8 -*-
"""Unemployment Analysis with Python (CODEALPHA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZd5L-WO0fQcvqdYzfMM2uvqtznKVEUo

✅ **TASK 2: Unemployment Analysis with Python**

● Analyze unemployment rate data representing


unemployed people percentage.

● Use Python for data cleaning, exploration, and visualization of unemployment trends.

● Investigate the impact of Covid-19 on unemployment rates.

● Identify key patterns or seasonal trends in the data.

present insights that can inform economics or social

policies

✅ **TASK 2: Unemployment Analysis with Python**

● Analyze unemployment rate data representing


unemployed people percentage.

● Use Python for data cleaning, exploration, and visualization of unemployment trends.

● Investigate the impact of Covid-19 on unemployment rates.

● Identify key patterns or seasonal trends in the data.

present insights that can inform economics or social

policies

✅ **TASK 2: Unemployment Analysis with Python**

● Analyze unemployment rate data representing


unemployed people percentage.

● Use Python for data cleaning, exploration, and visualization of unemployment trends.

● Investigate the impact of Covid-19 on unemployment rates.

● Identify key patterns or seasonal trends in the data.

present insights that can inform economics or social

policies
"""

# 1. Import Libraries
import pandas as pd
import matplotlib.pyplot as plt

# 2. Load Dataset
df = pd.read_csv("/content/Unemployment in India.csv")

df.info()

"""**CLEANING**"""

# 3. Data Cleaning
df.columns = df.columns.str.strip()

# remove extra spaces in column names
df = df.dropna()

# remove missing values
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

"""***EDA***"""

# 4. Exploratory Data Analysis
df.head()

df.describe()

# 5. Aggregate Unemployment Rate by Date (National Average)
time_series = df.groupby('Date')['Estimated Unemployment Rate (%)'].mean().reset_index()

# 6. Visualization: Unemployment Trend Over Time
plt.figure()

plt.plot(time_series['Date'], time_series['Estimated Unemployment Rate (%)'])
plt.title("Average Unemployment Rate in India Over Time")
plt.xlabel("Date")
plt.ylabel("Unemployment Rate (%)")
plt.show()

# 7. Covid-19 Impact Analysis
pre_covid = time_series[time_series['Date'] < '2020-03-01']
covid = time_series[(time_series['Date'] >= '2020-03-01') &
                    (time_series['Date'] <= '2021-06-01')]

pre_covid_avg = pre_covid['Estimated Unemployment Rate (%)'].mean()
covid_avg = covid['Estimated Unemployment Rate (%)'].mean()

print("Average Unemployment Rate (Pre-Covid):", round(pre_covid_avg, 2), "%")
print("Average Unemployment Rate (During Covid):", round(covid_avg, 2), "%")

# 8. Rural vs Urban Comparison
area_avg = df.groupby('Area')['Estimated Unemployment Rate (%)'].mean()
print(area_avg)

# 9. Monthly Trend (Seasonality Check)
df['Month'] = df['Date'].dt.month
monthly_avg = df.groupby('Month')['Estimated Unemployment Rate (%)'].mean()

plt.figure()
plt.plot(monthly_avg.index, monthly_avg.values)
plt.title("Monthly Average Unemployment Rate")
plt.xlabel("Month")
plt.ylabel("Unemployment Rate (%)")
plt.show()

"""Summary Report: Unemployment Rate Analysis (India)

This study analyzes unemployment rate data in India to understand overall trends, seasonal patterns, and the impact of the Covid-19 pandemic. Python was used for data cleaning, analysis, and visualization.

Before 2020, unemployment rates remained relatively stable at around 9–10%, with minor fluctuations indicating seasonal employment patterns, especially in rural and agricultural sectors. However, during the Covid-19 lockdown period in 2020, unemployment increased sharply, reaching its highest levels due to business closures and restrictions on economic activity.

A comparison of pre-Covid and Covid periods shows that the average unemployment rate nearly doubled during the pandemic. Urban areas were more severely affected than rural areas, while recovery after lockdowns was gradual and uneven.

The findings highlight that Covid-19 caused a major disruption to the labor market, overriding normal seasonal trends. These insights emphasize the need for strong employment support programs, social protection policies, and skill development initiatives to reduce the impact of future economic shocks
"""

